language: php

dist: xenial

services:
  - mysql

addons:
  apt:
    packages:
      - tidy

env:
  global:
    - COMPOSER_ROOT_VERSION=3.0.x-dev

matrix:
  include:
   - php: 7.3
     env: DB=MYSQL CORE_RELEASE=4.4 PDO=1

before_script:
 - phpenv rehash
 - phpenv config-rm xdebug.ini
 - composer validate
 - composer require --prefer-source --no-update silverstripe/recipe-cms:^4
 - composer require silverstripe/vendor-plugin:^1.0 silvershop/silverstripe-listsorter:^3@dev silvershop/silverstripe-sqlquerylist:^2@dev php-http/buzz-adapter omnipay/common:^3.0.2 silverstripe/silverstripe-omnipay:3@dev silvershop/core:^3.0.2 --no-update --prefer-dist --prefer-stable
 - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
 - vendor/bin/phpunit
